# Generated by Django 5.1.4 on 2025-01-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(),
        ),
    ]
