# Generated by Django 5.1.4 on 2025-01-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productcomment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='user_name',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcomment',
            name='full_name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcomment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
